/* oxlint-disable max-lines */
import { createHash } from "node:crypto";

import { minimatch } from "minimatch";

import type { ProjectPolicy, ValidationCommand } from "./project-policy.js";
import type {
  CandidateDraft,
  MaterialFinding,
  ReviewedPullRequest,
  VerificationAdapter,
} from "./review-orchestration.js";

export const SUGGESTED_PATCH_MAX_LINES = 20;
export const SUGGESTED_PATCH_MAX_BYTES = 16 * 1024;
export const SUGGESTED_PATCH_SECURITY = {
  network: "denied",
  secrets: "denied",
  memoryBytes: 1024 * 1024 * 1024,
  cpuCount: 2,
  processLimit: 128,
  temporaryBytes: 64 * 1024 * 1024,
  workspace: "read_only",
} as const;

export interface SuggestedPatchProposal {
  startLine: number;
  endLine: number;
  replacement: string;
}

export interface SuggestedPatchValidation {
  commandIndex: number;
  commandHash: string;
  status: "passed";
}

export interface SuggestedPatch {
  id: string;
  path: string;
  startLine: number;
  endLine: number;
  replacement: string;
  reviewedHeadSha: string;
  sourceHash: string;
  validation: SuggestedPatchValidation;
}

export interface SuggestedPatchValidationRequest {
  repository: string;
  headSha: string;
  path: string;
  startLine: number;
  endLine: number;
  expected: string;
  replacement: string;
  sandboxImage: string;
  command: ValidationCommand & { commandIndex: number };
  security: typeof SUGGESTED_PATCH_SECURITY;
  signal: AbortSignal;
}

export type SuggestedPatchValidationResult = {
  status: "passed" | "failed" | "timed_out" | "aborted" | "stale" | "unavailable" | "error";
  exitCode?: number | undefined;
  stdout: string;
  stderr: string;
  truncated: boolean;
  limitation?: string | undefined;
};

function hash(value: string): string {
  return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

function lineCount(value: string): number {
  return value.length === 0 ? 0 : value.split("\n").length;
}

function sourceLines(value: string): string[] | undefined {
  if (
    value.includes("\0") ||
    value.includes("�") ||
    /(?:@generated|auto[- ]generated|code generated.{0,120}do not edit|generated by)/iu.test(
      value.slice(0, 8 * 1024),
    )
  ) {
    return undefined;
  }
  const normalized = value.replaceAll("\r\n", "\n");
  const lines = normalized.split("\n");
  if (lines.at(-1) === "") lines.pop();
  return lines;
}

const prohibitedBasenames = new Set([
  "package.json",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "deno.lock",
  "pyproject.toml",
  "deps.edn",
  "bb.edn",
  "project.clj",
  "build.sbt",
  "setup.py",
  "setup.cfg",
  "tox.ini",
  "poetry.lock",
  "pdm.lock",
  "uv.lock",
  "pipfile",
  "pipfile.lock",
  "requirements.txt",
  "gemfile",
  "gemfile.lock",
  "cargo.toml",
  "cargo.lock",
  "go.mod",
  "go.sum",
  "mix.exs",
  "mix.lock",
  "pubspec.yaml",
  "pubspec.lock",
  "composer.json",
  "composer.lock",
  "pom.xml",
  "gradle.lockfile",
  "packages.lock.json",
  "go.work",
  "go.work.sum",
  "package.swift",
  "package.resolved",
  "podfile",
  "podfile.lock",
  "cartfile",
  "cartfile.resolved",
  "packages.config",
  "directory.packages.props",
  "build.gradle",
  "build.gradle.kts",
  "settings.gradle",
  "settings.gradle.kts",
  "gradle.properties",
  "module.bazel",
  "workspace",
  "workspace.bazel",
  "flake.nix",
  "flake.lock",
  "action.yml",
  "action.yaml",
  ".npmrc",
  ".yarnrc",
  ".yarnrc.yml",
  ".pypirc",
  ".netrc",
  ".woodpecker.yml",
  ".woodpecker.yaml",
  ".drone.yml",
  ".drone.yaml",
  "jenkinsfile",
  "azure-pipelines.yml",
  "azure-pipelines.yaml",
  "bitbucket-pipelines.yml",
  "bitbucket-pipelines.yaml",
  ".travis.yml",
  ".travis.yaml",
  "codeowners",
]);

// Eligibility necessarily combines the independent prohibited path classes from policy.
// oxlint-disable-next-line complexity
export function prohibitedSuggestedPatchPath(path: string): boolean {
  const normalized = path.replaceAll("\\", "/").toLowerCase();
  const basename = normalized.split("/").at(-1) ?? "";
  if (
    normalized.startsWith("/") ||
    normalized.includes("../") ||
    normalized.includes("//") ||
    [...normalized].some(
      (character) => (character.codePointAt(0) ?? 0) < 32 || [",", ":"].includes(character),
    )
  ) {
    return true;
  }
  if (
    normalized.startsWith(".github/") ||
    normalized.startsWith(".gitlab/") ||
    normalized.startsWith(".circleci/") ||
    normalized.startsWith(".buildkite/") ||
    normalized.startsWith(".tekton/") ||
    normalized.startsWith(".dagger/") ||
    /(^|\/)(?:vendor|vendored|third_party|node_modules|generated|dist|build|coverage)(?:\/|$)/u.test(
      normalized,
    )
  ) {
    return true;
  }
  if (
    prohibitedBasenames.has(basename) ||
    /^requirements(?:[.-].*)?\.(?:in|txt)$/u.test(basename) ||
    /(?:^|\.)(?:gen|generated)\.[^.]+$/u.test(basename) ||
    /\.pb\.(?:cc|cs|go|h|java|js|py|rb|rs|ts)$/u.test(basename)
  ) {
    return true;
  }
  return (
    /^\.env(?:\.|$)/u.test(basename) ||
    /(?:credential|credentials|secret|secrets|password|passwd|permission|permissions)/u.test(
      basename,
    ) ||
    /\.(?:pem|key|p12|pfx|crt|cer|der|lock|csproj|fsproj|vbproj)$/u.test(basename) ||
    /(?:^|[-_.])lock(?:file)?$/u.test(basename)
  );
}

interface DiffFile {
  path: string;
  addedLines: Set<number>;
  ineligible: boolean;
}

// Unified-diff parsing branches on file metadata, hunks, and line prefixes.
// oxlint-disable-next-line complexity
function diffFiles(diff: string): Map<string, DiffFile> {
  const files = new Map<string, DiffFile>();
  let current: DiffFile | undefined;
  let headLine: number | undefined;
  for (const line of diff.split("\n")) {
    if (line.startsWith("diff --git ")) {
      const match = /^diff --git a\/(.+) b\/(.+)$/u.exec(line);
      current =
        match === null ? undefined : { path: match[2]!, addedLines: new Set(), ineligible: false };
      if (current !== undefined) files.set(current.path, current);
      headLine = undefined;
      continue;
    }
    if (current === undefined) continue;
    if (
      /^(?:new file mode|deleted file mode|old mode|new mode|rename from|rename to|similarity index|GIT binary patch|Binary files )/u.test(
        line,
      ) ||
      /^(?:index )?\w+\.\.\w+ 1[26]0000$/u.test(line)
    ) {
      current.ineligible = true;
    }
    const hunk = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/u.exec(line);
    if (hunk !== null) {
      headLine = Number(hunk[1]);
      continue;
    }
    if (headLine === undefined || line.startsWith("\\")) continue;
    if (line.startsWith("+")) current.addedLines.add(headLine);
    if (!line.startsWith("-")) headLine += 1;
  }
  return files;
}

function selectedCommand(
  path: string,
  policy: ProjectPolicy,
): { commandIndex: number; command: ValidationCommand; sandboxImage: string } | undefined {
  const configuration = policy.verification.suggestedPatches;
  if (configuration === undefined) return undefined;
  const rule = configuration.validationRules.find(({ includePaths }) =>
    includePaths.some((pattern) => minimatch(path, pattern, { dot: true })),
  );
  if (rule === undefined) return undefined;
  const command = policy.verification.validationCommands[rule.commandIndex];
  return command === undefined
    ? undefined
    : { commandIndex: rule.commandIndex, command, sandboxImage: configuration.sandboxImage };
}

function proposalWithinFinding(
  proposal: SuggestedPatchProposal,
  finding: MaterialFinding,
): boolean {
  const findingEnd = finding.location.line;
  if (findingEnd === undefined) return false;
  const findingStart = finding.location.startLine ?? findingEnd;
  return proposal.startLine >= findingStart && proposal.endLine <= findingEnd;
}

// All independent safety ceilings must pass before any executable validation.
// oxlint-disable-next-line complexity
function eligibleProposal(
  candidate: CandidateDraft | undefined,
  finding: MaterialFinding,
  file: DiffFile | undefined,
): SuggestedPatchProposal | undefined {
  const proposal = candidate?.suggestedPatch;
  if (
    proposal === undefined ||
    file === undefined ||
    file.ineligible ||
    prohibitedSuggestedPatchPath(finding.location.path) ||
    candidate?.location.path !== finding.location.path ||
    !Number.isInteger(proposal.startLine) ||
    !Number.isInteger(proposal.endLine) ||
    proposal.startLine <= 0 ||
    proposal.endLine < proposal.startLine ||
    proposal.endLine - proposal.startLine + 1 > SUGGESTED_PATCH_MAX_LINES ||
    lineCount(proposal.replacement) > SUGGESTED_PATCH_MAX_LINES ||
    Buffer.byteLength(proposal.replacement) > SUGGESTED_PATCH_MAX_BYTES ||
    proposal.replacement.includes("\0") ||
    proposal.replacement.includes("```") ||
    !proposalWithinFinding(proposal, finding)
  ) {
    return undefined;
  }
  for (let line = proposal.startLine; line <= proposal.endLine; line += 1) {
    if (!file.addedLines.has(line)) return undefined;
  }
  return proposal;
}

function overlaps(
  occupied: ReadonlyMap<string, Array<{ startLine: number; endLine: number }>>,
  path: string,
  startLine: number,
  endLine: number,
): boolean {
  return (occupied.get(path) ?? []).some(
    (range) => startLine <= range.endLine && endLine >= range.startLine,
  );
}

// Patch validation is intentionally best-effort: any failure leaves the Finding actionable.
// oxlint-disable-next-line complexity, max-lines-per-function
export async function attachSuggestedPatches(input: {
  pullRequest: ReviewedPullRequest;
  diff: string;
  policy: ProjectPolicy;
  candidatesByFingerprint: ReadonlyMap<string, CandidateDraft>;
  findings: MaterialFinding[];
  adapter: VerificationAdapter;
  signal: AbortSignal;
}): Promise<void> {
  if (input.adapter.validateSuggestedPatch === undefined) return;
  const files = diffFiles(input.diff);
  const occupied = new Map<string, Array<{ startLine: number; endLine: number }>>();
  for (const finding of input.findings) {
    if (!["new", "persisting", "accepted"].includes(finding.lifecycleState)) continue;
    const candidate = input.candidatesByFingerprint.get(finding.fingerprint.value);
    const file = files.get(finding.location.path);
    const proposal = eligibleProposal(candidate, finding, file);
    const selected = selectedCommand(finding.location.path, input.policy);
    if (
      proposal === undefined ||
      selected === undefined ||
      overlaps(occupied, finding.location.path, proposal.startLine, proposal.endLine)
    ) {
      continue;
    }
    let repositoryFile: Awaited<ReturnType<VerificationAdapter["readRepositoryFile"]>>;
    try {
      // Reads are sequential with validation to keep patch resource use bounded.
      // oxlint-disable-next-line no-await-in-loop
      repositoryFile = await input.adapter.readRepositoryFile({
        repository: input.pullRequest.repository,
        headSha: input.pullRequest.headSha,
        path: finding.location.path,
        maxBytes: 64 * 1024,
        signal: input.signal,
      });
    } catch {
      continue;
    }
    if (repositoryFile === undefined || repositoryFile.truncated) continue;
    const lines = sourceLines(repositoryFile.content);
    if (lines === undefined || proposal.endLine > lines.length) continue;
    const expected = lines.slice(proposal.startLine - 1, proposal.endLine).join("\n");
    if (expected === proposal.replacement) continue;
    let result: SuggestedPatchValidationResult;
    try {
      // Validation is sequential so one Finding cannot multiply container resource ceilings.
      // oxlint-disable-next-line no-await-in-loop
      result = await input.adapter.validateSuggestedPatch({
        repository: input.pullRequest.repository,
        headSha: input.pullRequest.headSha,
        path: finding.location.path,
        startLine: proposal.startLine,
        endLine: proposal.endLine,
        expected,
        replacement: proposal.replacement,
        sandboxImage: selected.sandboxImage,
        command: { ...selected.command, commandIndex: selected.commandIndex },
        security: SUGGESTED_PATCH_SECURITY,
        signal: input.signal,
      });
    } catch {
      continue;
    }
    if (result.status !== "passed") continue;
    const sourceHash = hash(repositoryFile.content);
    const commandHash = hash(JSON.stringify(selected.command.argv));
    finding.suggestedPatch = {
      id: hash(
        JSON.stringify({
          headSha: input.pullRequest.headSha,
          path: finding.location.path,
          startLine: proposal.startLine,
          endLine: proposal.endLine,
          replacement: proposal.replacement,
          sourceHash,
          commandHash,
        }),
      ),
      path: finding.location.path,
      startLine: proposal.startLine,
      endLine: proposal.endLine,
      replacement: proposal.replacement,
      reviewedHeadSha: input.pullRequest.headSha,
      sourceHash,
      validation: { commandIndex: selected.commandIndex, commandHash, status: "passed" },
    };
    const ranges = occupied.get(finding.location.path) ?? [];
    ranges.push({ startLine: proposal.startLine, endLine: proposal.endLine });
    occupied.set(finding.location.path, ranges);
  }
}

// The publisher repeats every data-only invariant before rendering executable suggestion syntax.
// oxlint-disable-next-line complexity
export function validSuggestedPatchForPublication(
  finding: MaterialFinding,
  headSha: string,
  changedLines: ReadonlySet<string>,
): SuggestedPatch | undefined {
  const patch = finding.suggestedPatch;
  if (
    patch === undefined ||
    patch.path !== finding.location.path ||
    patch.reviewedHeadSha !== headSha ||
    patch.validation.status !== "passed" ||
    !/^sha256:[\da-f]{64}$/u.test(patch.id) ||
    !/^sha256:[\da-f]{64}$/u.test(patch.sourceHash) ||
    !/^sha256:[\da-f]{64}$/u.test(patch.validation.commandHash) ||
    !Number.isInteger(patch.startLine) ||
    !Number.isInteger(patch.endLine) ||
    patch.startLine <= 0 ||
    patch.endLine < patch.startLine ||
    patch.endLine - patch.startLine + 1 > SUGGESTED_PATCH_MAX_LINES ||
    lineCount(patch.replacement) > SUGGESTED_PATCH_MAX_LINES ||
    Buffer.byteLength(patch.replacement) > SUGGESTED_PATCH_MAX_BYTES ||
    patch.replacement.includes("\0") ||
    patch.replacement.includes("```") ||
    prohibitedSuggestedPatchPath(patch.path)
  ) {
    return undefined;
  }
  const findingEnd = finding.location.line;
  const findingStart = finding.location.startLine ?? findingEnd;
  if (
    findingStart === undefined ||
    findingEnd === undefined ||
    patch.startLine < findingStart ||
    patch.endLine > findingEnd
  ) {
    return undefined;
  }
  for (let line = patch.startLine; line <= patch.endLine; line += 1) {
    if (!changedLines.has(`${patch.path}\0${line}`)) return undefined;
  }
  return patch;
}
